### ISSUE TITLE
Health Check Endpoint

### ISSUE THREAD

**Issue by hempels** [fullstorydev/relay-core#6]
Running Relay behind a load balancer would be easier if it supported an HTTP(S) health-check endpoint that returns a non-failure code and doesn't inadvertently check the health of a relay target. Is something like that possible using existing config options?

**Comment by TrevorFSmith** [comment]
Hi, there is an endpoint specifically for this: `/__relay__up__/`

There's currently no way to configure it to a different URL but hopefully the existing one will serve your purpose.

**Comment by hempels** [comment]
That's perfect. Thank you.
